  name: DevOps
  href: 
  items:
  - name: Introduction
    items:
      - name: Product Overview
        href: Introduction/Product-Overview.md
      - name: Core Concept
        href: Introduction/Core-Concepts.md
      - name: Basic Infrastructure
        href: Introduction/Basic-Infrastructure.md
      - name: Benefits
        href: Introduction/Benefits.md
      - name: Features
        href: Introduction/Features.md
      - name: Specifications
        href: Introduction/Specifications.md
      - name: Restrictions
        href: Introduction/Restrictions.md
      - name: Application Scenarios
        href: Introduction/Application-Scenarios.md    
  - name: Pricing
    items:
      - name: Billing Overview
        href: Pricing/Billing-Overview.md
      - name: Billing Rules
        href: Pricing/Billing-Rules.md
      - name: Price Overview
        href: Pricing/Price-Overview.md
      - name: Purchase Process
        href: Pricing/Purchase-Process.md 
      - name: Renew-Process
        href: Pricing/Renew-Process.md
  - name: Getting Started
    items:
      - name: Getting Started Guide
        href: Getting-Started/Getting-started.md
      - name: Install Super Agents in the Virtual Machines
        href: Getting-Started/Install-Agent.md
      - name: Create Service Tree Nodes
        href: Getting-Started/Create-Instance.md
      - name: import JD Cloud virtual machines
        href: Getting-Started/Import-Source.md
      - name: Create Construction Task
        href: Getting-Started/Create-Compilejob.md
      - name: Configure Online Release
        href: Getting-Started/Config-Deployment.md
      - name: Intelligent Access Monitoring
        href: Getting-Started/Quick-start-monitoring.md
  - name: Operation Guide
    items:
      - name: Introduction
        href: Operation-Guide/Operation-Instruction.md
      - name: Get to Know the Main interface of DevOps
        href: Operation-Guide/Introduction-index.md
      - name: Service Tree
        href: Operation-Guide/Service-Tree.md
      - name: Resource Pool
        href: Operation-Guide/Resource-Pool.md
      - name: Specification Template
        href: Operation-Guide/Specification-Templates.md
      - name: Compile and construct
        href: Operation-Guide/CI.md
      - name: On-line release
        href: Operation-Guide/CD.md
      - name: Arrange on-line
        href: Operation-Guide/Arrange-Online.md
      - name: Acquisition Configuration
        items:
          - name: Machine Monitoring
            href: Operation-Guide/Collection-Conf/Machine-Monitoring.md
          - name: Port Monitoring
            href: Operation-Guide/Collection-Conf/Port-Monitoring.md
          - name: Process Monitoring
            href: Operation-Guide/Collection-Conf/Process-Monitoring.md
          - name: Log Monitoring
            href: Operation-Guide/Collection-Conf/Log-Monitoring.md
          - name: Domain Name Monitoring
            href: Operation-Guide/Collection-Conf/Domain-Monitoring.md
          - name: Custom Metric Monitoring
            href: Operation-Guide/Collection-Conf/Custom-Monitoring.md
      - name: Aggregation Configuration
        href: Operation-Guide/Converge.md
      - name: Data Visualization
        href: Operation-Guide/Data-Visualization.md
      - name: Alarm Group & Duty Group
        href: Operation-Guide/Alarm-Contacts.md
      - name: Alarm Configuration
        href: Operation-Guide/Alarm-Conf.md
      - name: Alarm Management
        href: Operation-Guide/Alarm-Management.md
      - name: Tags Instructions
        href: Operation-Guide/Tags.md
      - name: Image Packaging
        href: Operation-Guide/Image-Packaging.md
      - name: Script Management
        href: Operation-Guide/Script.md
      - name: File Distribution
        href: Operation-Guide/File-Distribution.md
      - name: Account Management
        href: Operation-Guide/Account-management.md
  - name: Troubleshooting
    items:
      - name: Configuration Questions
        href: Troubleshooting/Configuration.md
  - name: FAQ
    href: FAQ/FAQ.md
  - name: API Reference
    href: API/API-Reference.md
  - name: SDK Reference
    href: SDK/SDK-Reference.md
  - name: User Agreement
    items:
      - name: Terms of Service
        href: User-Agreements/Product-Terms-of-Service.md                 
      - name: SLA
        href: User-Agreements/SLA.md               
  - name: Related Resources
    items:
      - name: Document History
        href: Related-Resources/Document-History.md                
      - name: Glossary
        href: Related-Resources/Glossary.md           
